server:
  port: 9001
eureka:
  instance:
    hostname: spring-cloud-eureka
    appname: spring-cloud-examples-eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000