#开发环境配置
server:
  port: 9901 #开发环境端口
eureka:
  instance:
    hostname: spring-cloud-eureka-dev
    appname: spring-cloud-examples-eureka-dev
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9901/eureka-dev
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000