#生产环境配置
server:
  port: 9902 #生产环境端口
eureka:
  instance:
    hostname: spring-cloud-eureka-prod
    appname: spring-cloud-examples-eureka-prod
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9902/eureka-prod
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000