server:
  port: 9005
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
spring:
  application:
    name: spring-cloud-eureka-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #自动路由
          enabled: true
          #服务名称全部小写
          lower-case-service-id: true
      routes:
        - id: spring-cloud-eureka-service-proxy #路由器ID
          uri: lb://spring-cloud-eureka-service
          predicates:
            - Path=/springCloudEurekaServiceProxy/**
          filters:
            - StripPrefix=1